
typedef enum behaior_type 
{
	BEHAVIOR_SHORT_CONN,
	BEHAVIOR_PERSISTENT_CONN,
	BEHAVIOR_NO_BLOCK,
	BEHAVIOR_TCP_NODELAY,
	BEHAVIOR_SOCKET_SEND_SIZE,
	BEHAVIOR_SOCKET_RECV_SIZE,
	BEHAVIOR_CONNECT_TIMEOUT,
	BEHAVIOR_RETRY_TIMEOUT,
	BEHAVIOR_SND_TIMEOUT,
	BEHAVIOR_RCV_TIMEOUT,
	BEHAVIOR_USE_UDP,
}
BEHAVIOR_TYPE;